Numpy: 数值计算，数组化
Scipy: 在Numpy基础上添加科学计算函数库
Matplotlib:绘图
两种基本对象：ndarray,ufunc
1.ndarray 对象
1.1 创建数组：通过给array函数传递序列对象
shape:表示数组形状，是一个描述数值各个轴长度的元组(tuple)
dtype:元素类型

In [1]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [2]:
a.shape

(4,)

In [4]:
b=np.array((2,3,4,5))
b

array([2, 3, 4, 5])

In [5]:
b.shape

(4,)

In [6]:
c=np.array([[1,2,3,4],[5,6,7,8],[5,3,3,2]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 3, 3, 2]])

In [7]:
c.shape

(3, 4)

In [8]:
c=np.array(([1,2,3,4],[5,6,7,8],[5,3,3,2]))
c
    

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 3, 3, 2]])

In [9]:
c.shape

(3, 4)

In [10]:
c.shape=4,3
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 5],
       [3, 3, 2]])

In [11]:
c.shape=2,-1
c

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 5, 3, 3, 2]])

In [12]:
c.shape

(2, 6)

In [13]:
d=a.reshape(2,2)
d

array([[1, 2],
       [3, 4]])

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a[1]=100
a

array([  1, 100,   3,   4])

In [16]:
d

array([[  1, 100],
       [  3,   4]])

In [17]:
c.dtype

dtype('int32')

In [18]:
np.array([4,3,4,2],dtype=np.float)

array([ 4.,  3.,  4.,  2.])

In [19]:
np.array([4,3,4,2],dtype=np.complex)

array([ 4.+0.j,  3.+0.j,  4.+0.j,  2.+0.j])

In [22]:
set(np.typeDict.values())


{numpy.uint32,
 numpy.str_,
 numpy.datetime64,
 numpy.float32,
 numpy.bool_,
 numpy.float64,
 numpy.complex128,
 numpy.float16,
 numpy.bytes_,
 numpy.uint16,
 numpy.complex64,
 numpy.complex128,
 numpy.timedelta64,
 numpy.int32,
 numpy.uint8,
 numpy.float64,
 numpy.void,
 numpy.int64,
 numpy.uint32,
 numpy.object_,
 numpy.int8,
 numpy.int32,
 numpy.uint64,
 numpy.int16}

In [23]:
np.arange(1,10,1) # 开始，终值，步长，等差数列，注意不含终值，

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.linspace(0,1,10)#开始，终值，个数，等差数列

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [28]:
np.linspace(0,1,10,endpoint=False)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [29]:
np.logspace(0,2,5) # 10次方，开始，终值，个数，等比数列，

array([   1.        ,    3.16227766,   10.        ,   31.6227766 ,  100.        ])

In [30]:
np.logspace(0,1,12,base=2,endpoint=False)

array([ 1.        ,  1.05946309,  1.12246205,  1.18920712,  1.25992105,
        1.33483985,  1.41421356,  1.49830708,  1.58740105,  1.68179283,
        1.78179744,  1.88774863])

In [32]:
d=np.empty((2,3),np.int)

In [33]:
d

array([[2036400220, 1802071135, 1931488357],
       [1701863784,  743254048, 1919885353]])

In [42]:
d=np.zeros((3,4),np.int)

In [43]:
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

1.2.读取数组
与列表相同
切片：是视图，与原数组共享数据存储空间

In [47]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a[5],a[3:5],a[:4],a[-1],a[:-1]

(5, array([3, 4]), array([0, 1, 2, 3]), 9, array([0, 1, 2, 3, 4, 5, 6, 7, 8]))

1.3 多维数组


In [53]:
a=np.arange(0,60,10).reshape(-1,1)+np.arange(0,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [54]:
a[0,3:5]

array([3, 4])

In [55]:
a[(0,1,2,3),(1,2,3,4)]

array([ 1, 12, 23, 34])

2.ufunc运算